CREATE TABLE Countries
(Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) UNIQUE NOT NULL)

CREATE TABLE Customers
(Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(25) NOT NULL,
LastName NVARCHAR(25) NOT NULL,
Gender CHAR(1) NOT NULL CHECK (Gender IN ('M', 'F')),
Age INT NOT NULL,
PhoneNumber VARCHAR(10) CHECK (LEN(PhoneNumber) = 10),
CountryId INT FOREIGN KEY REFERENCES Countries(Id))

CREATE TABLE Products
(Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(25) UNIQUE NOT NULL,
[Description] NVARCHAR(250),
Recipe NVARCHAR(MAX) NOT NULL,
Price DECIMAL(15,2) NOT NULL CHECK(Price >= 0))

CREATE TABLE Feedbacks
(Id INT PRIMARY KEY IDENTITY,
[Description] NVARCHAR(255),
Rate DECIMAL(4,2) NOT NULL CHECK(Rate >= 0 AND Rate <= 10),
ProductId INT FOREIGN KEY REFERENCES Products(Id),
CustomerId INT FOREIGN KEY REFERENCES Customers(Id))

CREATE TABLE Distributors
(Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(25) UNIQUE NOT NULL,
AddressText NVARCHAR(30)  NOT NULL,
Summary NVARCHAR(200)  NOT NULL,
CountryId INT FOREIGN KEY REFERENCES Countries(Id))

CREATE TABLE Ingredients
(Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
[Description] NVARCHAR(200) NOT NULL,
OriginCountryId INT FOREIGN KEY REFERENCES Countries(Id),
DistributorId INT FOREIGN KEY REFERENCES Distributors(Id))

CREATE TABLE ProductsIngredients
(ProductId INT FOREIGN KEY REFERENCES Products(Id) NOT NULL,
IngredientId INT FOREIGN KEY REFERENCES Ingredients(Id) NOT NULL
PRIMARY KEY(ProductId, IngredientId))
